# Generated by Django 6.0.3 on 2026-03-22 16:47

from django.db import migrations, models


def backfill_email_verified(apps, schema_editor):
    Profile = apps.get_model("app", "Profile")
    Profile.objects.all().update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_notifications_preferences_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_email_verified, migrations.RunPython.noop),
    ]
