# Generated by Django 6.0.3 on 2026-03-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile_google_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verification_code_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
